jobs:
  nixCI:
    name: Nix CI
    permissions:
      actions: write
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v25
        with:
          nix_conf: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            substituters = https://cache.nixos.org/ https://nix-community.cachix.org https://cache.iog.io https://deemp.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= deemp.cachix.org-1:9shDxyR2ANqEPQEEYDL/xIOnoPwxHot21L5fiZnFL18=
            keep-outputs = true
      - name: Restore and cache Nix store
        uses: nix-community/cache-nix-action@v1
        with:
          key: nix-ubuntu-22.04-job-${{ hashfiles('**/flake.nix', '**/flake.lock') }}
          linux-gc-enabled: true
          linux-max-store-size: 1300000000
          restore-keys: |
            nix-ubuntu-22.04-job-
      - name: Remove old cache profiles
        run: rm -rf /nix/var/nix/profiles/cache
      - name: Configure git for github-actions
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
      - name: Format Nix files
        run: |-
          nix profile install .#format
          nix run .#format
      - name: Update flake locks
        run: |-
          nix profile install .#updateLocks
          nix run .#updateLocks
      - name: Commit & Push
        run: |-
          git add .
          git commit \
            -m "action" \
            -m "Format Nix files" \
            -m "Update flake locks" \
            || echo "commit failed!"
          git push
      - name: Clean npm cache
        run: |-
          nix profile install .#npmCleanCache
          nix run .#npmCleanCache
      - name: Cache app dependencies
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json', '**/*.dhall') }}
          path: |
            ~/.npm
            .spago
            output
          restore-keys: |
            "${{ runner.os }}-node-
      - name: Build app
        run: |-
          nix profile install .#buildGHPages
          nix run .#buildGHPages
      - name: Publish app on GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          force_orphan: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
      - name: Purge cache
        uses: deemp/purge-cache@v1
        with:
          accessed: false
          created: true
          debug: true
          max-age: 172800
name: Nix CI
"on":
  pull_request: {}
  push: {}
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: {}
